version: 1.7.0-{branch}-{build}

cache:
    - c:\ProgramData\chocolatey
    - c:\mysql-5.7.9-win32

services:
  - mysql
  - mongodb
  - mssql2014  

platform:
  - Win32
  - x64
  
      
configuration:
  - release
  - debug

install:
  - systeminfo
  - c:\cygwin\bin\uname -a
  - c:\cygwin\bin\cat /proc/cpuinfo
  - c:\cygwin\bin\cat /proc/meminfo
  - set
  - cinst cmake
#  chocolatey brokes jom, here's workaround
#  see https://github.com/jcfr/qt-easy-build/commit/6366f4275562bdaf4f686838600f46894579c41e)
  - ps: |
        if ($env:builder -eq "cmake")
        {
          $env:PATH = $env:ChocolateyInstall + "\bin" + ";" + $env:PATH
          $env:PATH = $env:ChocolateyInstall + "\lib\jom\content" + ";" + $env:PATH
        }
#  MySQL 32 bit is not available by default on AppVeyor
  - ps: |
        if ($platform -eq "Win32")
        {
            if (Test-Path "c:\mysql-5.7.9-win32") {
                echo "using mysql-5.7.9-win32 from cache"
            }
            else
            {
                echo "downloading mysql-5.7.9-win32"
                Invoke-WebRequest "http://dev.mysql.com/get/Downloads/MySQL-5.7/mysql-5.7.9-win32.zip" -OutFile mysql-5.7.9-win32.zip
                echo "installing mysql-5.7.9-win32"
                7z x -y mysql-5.7.9-win32.zip -oc:\
            }
        }

environment:
  bundling: bundled
    
  matrix:
#    - builder: cmake
#      ssl: Win32
#      vc: amd64_x86
#      target: x86

    - builder: 120
      linkmode: shared
      vc32: x86
      vc64: x86_amd64


   
before_build:
  - ps: |
      if ($env:builder -eq "120")
      {
          if ($env:platform -eq "Win32")
          {
            & "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" x86
            $env:archsize =
          }
          if ($env:platform -eq "x64")
          {
            & "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" x86_amd64
            $env:archsize = 64
          }
      }
      if ($env:builder -eq "140")
      {
          if ($env:platform -eq "Win32")
          {
            & "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86
          }
          if ($env:platform -eq "x64")
          {
            & "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_amd64
          }
      }
  
# MySQL
  - ps: |
      if ($env:platform -eq "Win32")
      {
          $env:INCLUDE = "C:\mysql-5.7.9-win32\include;" + $env:INCLUDE
          $env:LIB     = "C:\mysql-5.7.9-win32\lib;" + $env:LIB
      }
      if ($env:platform -eq "x64")
      {
          $env:INCLUDE = "C:\Program Files\MySql\MySQL Server 5.6\include;" + $env:INCLUDE
          $env:LIB     = "C:\Program Files\MySql\MySQL Server 5.6\lib;" + $env:LIB
      }

after_build:

build_script:
  - buildwin %builder% build %linkmode% %configuration% %platform% samples tests msbuild minimal "C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" 
  
before_test:
  - set PATH=%CD%\bin;%PATH%
  - set EXCLUDE_TESTS=NetSLL_Win,Data/ODBC,Data/MySQL

after_test:

test_script:
  - build\script\runtests2.cmd %archsize%
  
  
on_success:
  - echo success

on_failure:
  - echo failure

on_finish:
  - echo finish
  
  
notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false
    
      
  - provider: Slack
    auth_token:
      secure: xoOlP1UHshqjvh/INwMcNhZ5UHsTVKLGY5maTSjaxDc0fvRwoWIdYvY/CofQEuy2wOIBQK4eLD+tA0xG78ZgqQ==
    channel: poco
    on_build_success: false
    on_build_status_changed: false
  
  - provider: Slack
    incoming_webhook: https://hooks.slack.com/services/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
    