version: poco-{branch}-{build}

install:
  - cinst cmake

build_script:
  - set PATH=C:\Program Files\CMake\bin;C:\ProgramData\chocolatey\bin;%PATH%
  - cmake -H. -Bcmake-build -G"Visual Studio 16 2019" -DENABLE_DATA_MYSQL=OFF -DENABLE_DATA_POSTGRESQL=OFF
  - cmake --build cmake-build
